language: node_js
node_js:
  - node
before_install:
  - printf "@fortawesome:registry=https://npm.fontawesome.com/\n//npm.fontawesome.com/:_authToken=${FA_AUTH_TOKEN}" >> ~/.npmrc
  - npm install -g babel-cli
  - npm install
  before_deploy:
  - rm -rf node_modules
  deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY_ID
    secret_access_key: $AWS_SECRET_ACCESS_KEY
    bucket: 'planning-rco-notification-map-dev'
    on:
      branch: dev
    skip_cleanup: true
